### ISSUE TITLE
Max recursion depth error

### ISSUE THREAD

**Issue by AbeHandler** [fortytw0/needfinder#11]
If I run `python -m src.main` on the main branch I get a recursion error on `corpus.fit` in the `arora_similarity` module.

<img width="1227" alt="Screen Shot 2022-06-29 at 5 56 36 PM" src="https://user-images.githubusercontent.com/1252925/176565113-f6ae5f13-7606-4375-be22-16e968475abd.png">

There is a circular function call in the arora module, shown below 

<img width="605" alt="Screen Shot 2022-06-29 at 6 00 05 PM" src="https://user-images.githubusercontent.com/1252925/176565332-512bf7aa-4467-4c47-9c0f-fb755fa3be64.png">

**Comment by fortytw0** [comment]
Ohhhhhh my bad!

**Comment by fortytw0** [comment]
Could you recheck the issue, should be resolved with the following commit. 

The problem is I made minor refactors to my code to make it more readable, and assumed that it would work without any errors. 

https://github.com/fortytw0/needfinder/commit/d04d23febef1933d002b490dcb166e620a5de5cb

**Comment by AbeHandler** [comment]
I am still seeing the error on 7-7 after doing a pull on the main branch.

![Screen Shot 2022-07-07 at 10 13 45 AM](https://user-images.githubusercontent.com/1252925/177821470-7e57c863-c257-4378-b416-a30acfd9b6aa.png)

**Comment by AbeHandler** [comment]
With bugfix on Jul 7 eve a new error 

<img width="1170" alt="Screen Shot 2022-07-07 at 8 45 28 PM" src="https://user-images.githubusercontent.com/1252925/177906946-977f32f3-7246-4ae6-b66f-e0dfffbf8e5b.png">
